### ISSUE TITLE
SSH URLs in .gitmodules

### ISSUE THREAD

**Issue by kevinior** [embeddedartistry/gdtoa#17]
When trying to clone the latest version of embeddedartristry/libc on our build server I get errors because the submodule URLs are all SSH ones (git@github.com) and the builder account doesn't have a github account.

Would it be possible to either change the URLs to use HTTP or to use relative URLs so that the same protocol as was used for the top-level libc clone is used?

This affects:
embeddedartistry/libc/.gitmodules
embeddedartistry/gdtoa/.gitmodules

(Sorry, I forgot to create a separate issue in this repo yesterday)

**Comment by phillipjohnston** [comment]
Ah, sorry, I checked the meson-buildsystem submodule did not remember to check gdtoa 😓

**Comment by phillipjohnston** [comment]
Will confirm once merged into libc

**Comment by phillipjohnston** [comment]
Merged in
